events {
    worker_connections 5;
}

http {
    ## nginxがデフォルトで用意するMIMEタイプと拡張子のマッピングファイル
    include /etc/nginx/mime.types;
    ## APIサーバーのコンテナ名(api)とポート(8000)を指定
    upstream api_server {
        server api:8000;
    }

    server {
        # HTTPポートで待ち受け
        listen 80;

        # APIサーバーへのプロキシ設定
        location /api/ {
            # APIサーバーへリクエストを転送
            proxy_pass http://api_server/;
            
            #　電子ペーパー側のヘッダー
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location / {
            return 200 'Hello from Nginx!';
        }
    }
}