services:

  api:
    build:
      context: ./api 
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    env_file:
      - ./.env # 環境変数ファイル
    networks:
      - epaper-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Nginx設定ファイル
    depends_on:
      - api # 起動順序
    networks:
      - epaper-network

networks:
  epaper-network:
    driver: bridge